actuator:
  emitter: tcp://127.0.0.1:5555
  max_pulse: 1800
  min_pulse: 1100
  server_port: 5001
  trim: 0
  sensor_targets:
    _4286: 3000
    _7143: 2000
  throttle_rewrite:
    _4286: 0.6
    _7143: 0.8
  break_intensity: 5000
  sensor_mode: 'none'
configServer:
  emitter: tcp://127.0.0.1:5556
  mqtt: mqtt://127.0.0.1:1883
remote:
  server_port: 5001
  server_address: "127.0.0.1"
hardware:
  REMOTE_STEERING_PIN: 17
  REMOTE_THROTTLE_PIN: 27
  REMOTE_MODE_PIN: 0
  LED_RED: 16
  LED_GREEN: 21
  LED_BLUE: 20
  SONAR_TRIGGER: 0
  SONAR_ECHO: 0
