actuator:
  emitter: tcp://127.0.0.1:5555
  max_pulse: 1800
  min_pulse: 1100
  server_port: 5001
  trim: 0
throttle:
  sensor_mode: 'invert'
  sensor_targets:
    slow: 4500
    medium: 3500
    fast: 2000
  pid:            
    k_p: 0.25
    k_i: 0.01
    k_d: 0.01
  max_throttle: 1
  min_throttle: -1
configServer:
  emitter: tcp://127.0.0.1:5556
  mqtt: mqtt://127.0.0.1:1883
remote:
  server_port: 5001
  server_address: "127.0.0.1"
sonar:
  slowdown_limit: 100
  break_limit: 50
hardware:
  REMOTE_STEERING_PIN: 17
  REMOTE_THROTTLE_PIN: 27
  REMOTE_MODE_PIN: 0
  LED_RED: 16
  LED_GREEN: 21
  LED_BLUE: 20
  SONAR_TRIGGER: 0
  SONAR_ECHO: 0
