actuator:
  emitter: tcp://10.42.0.1:5555
  max_pulse: 1690
  min_pulse: 1000
  trim: -20
  sensor_mode: 'invert'
configServer:
  emitter: tcp://10.42.0.1:5556
  mqtt: mqtt://10.42.0.1:1883
remote:
  server_port: 5001
  server_address: "10.42.0.1"
hardware:
  REMOTE_MODE_PIN: 22
