actuator:
  emitter: tcp://10.42.0.1:5555
  max_pulse: 1630
  min_pulse: 1000
  trim: -20
throttle:
  sensor_mode: 'invert'
  sensor_targets:
#    slow: 4500
#    medium: 3500
#    fast: 2000
    slow: 4000
    medium: 4000
    fast: 4000
  pid:
    k_p: 0.1
    k_i: 0.01
    k_d: 0.001
configServer:
  emitter: tcp://10.42.0.1:5556
  mqtt: mqtt://10.42.0.1:1883
remote:
  server_port: 5001
  server_address: "10.42.0.1"
hardware:
  REMOTE_MODE_PIN: 22
  SONAR_TRIGGER: 7
  SONAR_ECHO: 1
