actuator:
  emitter: tcp://10.42.0.1:5555
  max_pulse: 1700
  min_pulse: 1000
  trim: -20
  sensor_mode: 'invert'
  sensor_targets:
    _4286: 3500
    _7143: 2500
  throttle_rewrite:
    _4286: 0.5
    _7143: 0.75
  break_intensity: 300
configServer:
  emitter: tcp://10.42.0.1:5556
  mqtt: mqtt://10.42.0.1:1883
remote:
  server_port: 5001
  server_address: "10.42.0.1"
hardware:
  REMOTE_MODE_PIN: 22
