actuator:
  emitter: tcp://10.42.0.1:5555
  max_pulse: 1750
  min_pulse: 1150
  trim: 20
configServer:
  emitter: tcp://10.42.0.1:5556
remote:
  server_port: 5001
  server_address: "10.42.0.1"
hardware:
  REMOTE_MODE_PIN: 22
